<?php
/**
 * Created by PhpStorm.
 * User: cz
 * Date: 2018/11/20
 * Time: 17:09
 */

namespace clip\web;


class AssetBundle extends \yii\web\AssetBundle
{
    /**
     * web通用资源类，默认app\assets\CommonAsset
     *
     * @var string
     */
    public $commonAsset = 'app\assets\CommonAsset';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        array_unshift($this->depends, $this->commonAsset);
    }
}